<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $reportTitle }} - RentWheels Admin</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }
        
        .header {
            background: linear-gradient(135deg, #dc3545, #6f42c1);
            color: white;
            padding: 20px;
            text-align: center;
            margin-bottom: 20px;
        }
        
        .header h1 {
            font-size: 24px;
            margin-bottom: 5px;
        }
        
        .header p {
            font-size: 14px;
            opacity: 0.9;
        }
        
        .admin-info {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        
        .admin-info table {
            width: 100%;
        }
        
        .admin-info td {
            padding: 5px 0;
        }
        
        .stats-grid {
            display: table;
            width: 100%;
            margin-bottom: 25px;
        }
        
        .stats-item {
            display: table-cell;
            text-align: center;
            background: #e3f2fd;
            padding: 15px;
            border: 1px solid #bbdefb;
            width: 20%;
        }
        
        .stats-number {
            font-size: 18px;
            font-weight: bold;
            color: #dc3545;
            display: block;
        }
        
        .stats-label {
            font-size: 11px;
            color: #666;
            margin-top: 5px;
        }
        
        .section {
            margin-bottom: 25px;
        }
        
        .section-title {
            background: #dc3545;
            color: white;
            padding: 10px 15px;
            font-size: 16px;
            font-weight: bold;
            margin-bottom: 15px;
        }
        
        .customer-item {
            border: 1px solid #ddd;
            margin-bottom: 15px;
            page-break-inside: avoid;
        }
        
        .customer-header {
            background: #f8f9fa;
            padding: 12px 15px;
            border-bottom: 1px solid #ddd;
        }
        
        .customer-header .customer-name {
            font-weight: bold;
            font-size: 14px;
            color: #dc3545;
        }
        
        .customer-header .customer-status {
            float: right;
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 10px;
            font-weight: bold;
            color: white;
        }
        
        .status-active { background-color: #28a745; }
        .status-suspended { background-color: #dc3545; }
        
        .customer-details {
            padding: 15px;
        }
        
        .detail-grid {
            display: table;
            width: 100%;
            margin-bottom: 10px;
        }
        
        .detail-row {
            display: table-row;
        }
        
        .detail-label {
            display: table-cell;
            font-weight: bold;
            width: 25%;
            padding: 5px 10px 5px 0;
            color: #666;
        }
        
        .detail-value {
            display: table-cell;
            padding: 5px 0;
        }
        
        .booking-info {
            background: #f1f8ff;
            padding: 10px;
            border-radius: 5px;
            margin: 10px 0;
        }
        
        .activity-info {
            background: #f0fff0;
            padding: 10px;
            border-radius: 5px;
            margin-top: 10px;
        }
        
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 2px solid #dc3545;
            text-align: center;
            color: #666;
            font-size: 11px;
        }
        
        .clearfix::after {
            content: "";
            display: table;
            clear: both;
        }
        
        @media print {
            .customer-item {
                page-break-inside: avoid;
            }
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>👥 {{ $reportTitle }}</h1>
        <p>Generated on {{ $generatedAt->format('F j, Y \a\t g:i A') }}</p>
    </div>

    <!-- Admin Information -->
    <div class="admin-info">
        <table>
            <tr>
                <td><strong>Generated By:</strong></td>
                <td>{{ $admin->name }}</td>
                <td><strong>Admin Email:</strong></td>
                <td>{{ $admin->email }}</td>
            </tr>
            <tr>
                <td><strong>Report Period:</strong></td>
                <td>{{ $reportPeriod ?? 'All Time' }}</td>
                <td><strong>Total Records:</strong></td>
                <td>{{ $customers->count() }}</td>
            </tr>
        </table>
    </div>

    <!-- Statistics Overview -->
    <div class="stats-grid clearfix">
        <div class="stats-item">
            <span class="stats-number">{{ $stats['totalCustomers'] }}</span>
            <div class="stats-label">Total Customers</div>
        </div>
        <div class="stats-item">
            <span class="stats-number">{{ $stats['activeCustomers'] }}</span>
            <div class="stats-label">Active Customers</div>
        </div>
        <div class="stats-item">
            <span class="stats-number">{{ $stats['suspendedCustomers'] }}</span>
            <div class="stats-label">Suspended</div>
        </div>
        <div class="stats-item">
            <span class="stats-number">{{ $stats['recentCustomers'] }}</span>
            <div class="stats-label">New This Month</div>
        </div>
        <div class="stats-item">
            <span class="stats-number">RM{{ number_format($stats['totalRevenue'], 2) }}</span>
            <div class="stats-label">Total Revenue</div>
        </div>
    </div>

    @if($customers->count() > 0)
        @foreach($groupedCustomers as $statusGroup => $groupCustomers)
            @if($groupCustomers->count() > 0)
            <div class="section">
                <div class="section-title">{{ $statusGroup }} Customers ({{ $groupCustomers->count() }})</div>
                
                @foreach($groupCustomers as $customer)
                <div class="customer-item">
                    <div class="customer-header clearfix">
                        <span class="customer-name">{{ $customer->name }}</span>
                        <span class="customer-status status-{{ strtolower($customer->status ?? 'active') }}">
                            {{ ucfirst($customer->status ?? 'Active') }}
                        </span>
                    </div>
                    
                    <div class="customer-details">
                        <!-- Customer Details -->
                        <div class="detail-grid">
                            <div class="detail-row">
                                <div class="detail-label">Email:</div>
                                <div class="detail-value">{{ $customer->email }}</div>
                                <div class="detail-label">Phone:</div>
                                <div class="detail-value">{{ $customer->phone ?? 'Not provided' }}</div>
                            </div>
                            <div class="detail-row">
                                <div class="detail-label">Date of Birth:</div>
                                <div class="detail-value">
                                    {{ $customer->date_of_birth ? \Carbon\Carbon::parse($customer->date_of_birth)->format('M j, Y') : 'Not provided' }}
                                </div>
                                <div class="detail-label">Address:</div>
                                <div class="detail-value">{{ $customer->address ?? 'Not provided' }}</div>
                            </div>
                            <div class="detail-row">
                                <div class="detail-label">Joined:</div>
                                <div class="detail-value">{{ $customer->created_at->format('M j, Y \a\t g:i A') }}</div>
                                <div class="detail-label">Last Update:</div>
                                <div class="detail-value">{{ $customer->updated_at->format('M j, Y \a\t g:i A') }}</div>
                            </div>
                            <div class="detail-row">
                                <div class="detail-label">Member Since:</div>
                                <div class="detail-value">{{ $customer->created_at->diffForHumans() }}</div>
                                <div class="detail-label">Customer ID:</div>
                                <div class="detail-value">#{{ str_pad($customer->id, 6, '0', STR_PAD_LEFT) }}</div>
                            </div>
                        </div>

                        <!-- Booking Activity -->
                        <div class="booking-info">
                            <strong>📊 Booking Activity:</strong><br>
                            <small>
                                Total Bookings: {{ $customer->bookings_count ?? 0 }} • 
                                Active: {{ $customer->active_bookings_count ?? 0 }} • 
                                Completed: {{ $customer->completed_bookings_count ?? 0 }}
                                @if($customer->last_booking_date)
                                    <br>Last Booking: {{ $customer->last_booking_date->format('M j, Y') }}
                                @endif
                            </small>
                        </div>

                        <!-- Revenue Information -->
                        @if(isset($customer->total_spent) && $customer->total_spent > 0)
                        <div class="activity-info">
                            <strong>💰 Revenue Information:</strong><br>
                            Total Spent: RM{{ number_format($customer->total_spent, 2) }}
                            @if(isset($customer->average_booking_value))
                                • Average Booking: RM{{ number_format($customer->average_booking_value, 2) }}
                            @endif
                        </div>
                        @endif
                    </div>
                </div>
                @endforeach
            </div>
            @endif
        @endforeach
    @else
        <div class="section">
            <div style="text-align: center; padding: 40px; color: #666;">
                <h3>No Customers Found</h3>
                <p>No customers match the specified criteria.</p>
            </div>
        </div>
    @endif

    <!-- Footer -->
    <div class="footer">
        <p><strong>RentWheels Vehicle Rental System - Admin Report</strong></p>
        <p>Customer Management & Analytics Dashboard</p>
        <p>For admin support, contact: admin@rentwheels.com | +60 12-345 6789</p>
        <p style="margin-top: 10px;">This report was generated automatically on {{ $generatedAt->format('F j, Y \a\t g:i A') }}</p>
    </div>
</body>
</html>